# Generated by Django 4.1.2 on 2022-11-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=11, null=True)),
                ("state", models.CharField(max_length=2, null=True)),
                ("street", models.CharField(max_length=50, null=True)),
                ("number", models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
