# Generated by Django 4.1.2 on 2022-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="cep",
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="number",
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="state",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
