# Generated by Django 4.1.2 on 2022-11-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_address_user_birth_date_user_clinic_user_cpf_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_recepcionist",
            new_name="is_receptionist",
        ),
    ]
