# Generated by Django 4.1.2 on 2022-11-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_clinic_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="clinic_name",
            field=models.CharField(max_length=126, unique=True),
        ),
    ]
